### ISSUE TITLE
destroy not working

### ISSUE THREAD

**Issue by beckend** [dy/resizable#2]
Coffescript syntax:

```
resizableInstance = new Resizable(mediaArchiveMenuEl.getElementsByClassName('myTarget')[0],
          within: 'parent'
          handles: 'e'
          threshold: 1
          draggable: false)
```

later on: `resizableInstance.destroy()`

TypeError: this.handles[hName].draggable.destroy is not a function
    at Resizable.proto.destroy (index.js:402)

**Comment by dy** [comment]
@beckend thanks for checking! Fixed by 3a1a362ba268ab1b79962a582bb71a01dfde522c
