### ISSUE TITLE
Element is dragged even with draggable: false

### ISSUE THREAD

**Issue by fiatjaf** [dy/resizable#3]
Although the [README](https://github.com/dfcreative/resizable/blob/3a1a362ba268ab1b79962a582bb71a01dfde522c/README.md#options) says:

| Parameter | Default | Description |
| --- | :-: | --- |
| `draggable` | `false` | Make element [draggable](http://github.com/dfcreative/draggy) as well. Set an object to pass options to draggable. |

I have an element to which I'm passing `draggable: false`, but it is being dragged anyway. It may be something related to [the following](https://github.com/dfcreative/resizable/blob/3a1a362ba268ab1b79962a582bb71a01dfde522c/index.js#L53-L57) draggable being created anyway:

``` javascript
        self.draggable = new Draggable(self.element, {
            handle: null
        });
```

I couldn't understand where exactly this was being used or if it is really a bug, but I added a `transform: none !important` to my CSS and it is working that way -- without allowing the element to be dragged.

**Comment by dy** [comment]
Hm. `{draggable: false}` works for me just fine.
Could you try updated `npm update resizable draggy`, and if it does not work - what browser/html do you use?
